name: Deployment Pipeline

on:
  push:
    branches: [main]

jobs:
  deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Bump version and push tag
        if: ${{ contains(join(github.event.commits.*.message, ' '), '#skip') == false }}
        uses: anothrNick/github-tag-action@eca2b69f9e2c24be7decccd0f15fdb1ea5906598
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_BRANCHES: main
          WITH_V: true
          DEFAULT_BUMP: patch

      - name: Install Dependencies
        if: ${{ contains(join(github.event.commits.*.message, ' '), '#skip') == false }}
        run: npm install

      - name: Build
        if: ${{ contains(join(github.event.commits.*.message, ' '), '#skip') == false }}
        run: npm run build

      - name: Deploy via FTP
        if: ${{ contains(join(github.event.commits.*.message, ' '), '#skip') == false }}
        uses: SamKirkland/FTP-Deploy-Action@2a4e9b1312ebeb73a1f72b9330c71831c1e4ce01
        with:
          server: ftpupload.net
          username: epiz_27587580
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build/
          server-dir: ./htdocs/
          dangerous-clean-slate: true

      - name: Slack Notification
        if: always()
        uses: 8398a7/action-slack@b6a4c791ce0c137843eb11e038f855cf567014dc
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}