name: Healthcheck

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  healthcheck:
    runs-on: ubuntu-latest
    steps:
    - name: Check the deployed service URL
      uses: jtalk/url-health-check-action@2ff10af730f912a7b51f4e3868d9cb30de170a6b
      with:
        # Check the following URLs one by one sequentially
        url: https://www.aubreynicoll.com/health
        # Follow redirects, or just report success on 3xx status codes
        follow-redirect: no # Optional, defaults to "no"
        # Fail this action after this many failed attempts
        max-attempts: 3 # Optional, defaults to 1
        # Delay between retries
        retry-delay: 10s # Optional, only applicable to max-attempts > 1
    
    - name: Slack Notification
        if: failure()
        uses: 8398a7/action-slack@b6a4c791ce0c137843eb11e038f855cf567014dc
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}